2021-05-19 13:49:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-19 13:57:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-19 13:57:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,登录名 admin 已经存在[0m

2021-05-19 14:05:23 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-19 14:06:11 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-19 14:06:16 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-19 14:07:24 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-19 14:07:24 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-19 14:08:38 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-19 14:08:38 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-19 14:09:42 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-19 14:42:02 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:24:22 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:24:58 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:25:35 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:27:51 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:27:55 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:30:23 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:30:31 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:36:00 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:36:04 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:36:15 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常：mouldlist matching query does not exist.[0m

2021-05-20 11:37:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:38:00 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:39:46 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:40:04 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:40:29 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:40:31 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:40:38 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常：mouldlist matching query does not exist.[0m

2021-05-20 11:41:32 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:41:36 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:41:40 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常：mouldlist matching query does not exist.[0m

2021-05-20 11:41:47 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常：mouldlist matching query does not exist.[0m

2021-05-20 11:43:17 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常：mouldlist matching query does not exist.[0m

2021-05-20 11:49:08 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:49:48 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 11:49:52 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 11:50:01 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常：mouldlist matching query does not exist.[0m

2021-05-20 12:32:52 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 12:40:03 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 12:40:22 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 12:40:26 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 12:40:32 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m该模板名称test已经存在[0m

2021-05-20 12:43:09 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:28:36 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:28:40 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 20:33:51 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:33:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 20:34:09 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:34:12 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 20:34:58 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:35:00 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 20:41:53 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:42:26 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:42:30 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m登出失败，发生未知异常:%b requires a bytes-like object, or an object that implements __bytes__, not 'str'[0m

2021-05-20 20:43:14 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:43:16 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:%b requires a bytes-like object, or an object that implements __bytes__, not 'str'[0m

2021-05-20 20:46:32 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:46:34 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:not enough arguments for format string[0m

2021-05-20 20:47:28 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:47:31 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:Incorrect AES key length (6 bytes)[0m

2021-05-20 20:49:01 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:49:03 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 20:58:41 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:58:52 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:Missing required parameter 'digestmod'.[0m

2021-05-20 20:59:34 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 20:59:36 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:00:19 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:00:21 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:07:56 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:07:59 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:Incorrect AES key length (18 bytes)[0m

2021-05-20 21:08:17 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:08:19 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:19:50 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:19:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:22:27 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:22:29 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:decrypt() cannot be called after encrypt()[0m

2021-05-20 21:24:23 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:24:25 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:25:10 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:25:12 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:27:51 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:27:54 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:31:34 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:31:36 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:34:19 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:34:22 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 21:34:29 - simple - "/home/awen/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m该模板名称test已经存在[0m

2021-05-20 21:53:48 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 21:54:01 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 22:13:20 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-20 22:13:23 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 22:13:24 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 22:13:24 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m
2021-05-20 22:13:25 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-20 22:13:25 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m
2021-05-20 22:13:26 - simple - "/home/awen/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-22 15:02:13 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-22 15:24:54 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-22 15:25:02 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m
2021-05-22 15:25:02 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生未知异常:Object of type bytes is not JSON serializable[0m

2021-05-22 15:25:48 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-22 15:25:50 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-22 15:27:55 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-22 15:27:57 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-22 15:34:24 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-22 15:34:27 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-22 15:47:25 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-22 15:49:04 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-23 14:58:11 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-23 14:58:14 - simple - "/home/awen/桌面/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 16:09:18 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:09:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 16:11:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:36:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:37:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:38:11 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:38:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:38:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:40:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:41:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：admin[0m

2021-05-25 16:42:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:43:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-25 16:43:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-25 16:43:26 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 16:43:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 16:46:35 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:46:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 16:49:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:49:23 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 16:55:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:55:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 16:58:19 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 16:58:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 16:59:25 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test1[0m

2021-05-25 17:13:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 17:13:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-25 17:13:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-25 17:14:13 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-25 17:14:13 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,昵称 test 已经存在[0m

2021-05-25 17:14:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-25 17:14:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-25 17:14:33 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m非管理员登陆，操作者为：test1[0m

2021-05-25 17:17:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 17:24:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 17:24:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 17:24:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test1[0m

2021-05-25 17:24:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test1[0m
2021-05-25 17:24:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户删除失败,发生未知异常:User matching query does not exist.[0m

2021-05-25 17:25:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 17:35:47 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:14:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:14:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:15:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:15:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:15:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:15:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:16:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:16:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:16:56 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:16:56 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:17:30 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:17:30 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:17:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:17:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:17:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:17:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:18:47 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:18:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:18:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:19:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:19:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:19:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:19:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:19:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:19:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m
2021-05-25 18:19:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:19:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:19:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:26:03 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:26:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:26:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:26:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:26:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:27:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:'Request' object has no attribute 'post'[0m

2021-05-25 18:29:19 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:29:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:29:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:byte indices must be integers or slices, not str[0m

2021-05-25 18:32:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:32:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:32:33 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:'Request' object has no attribute 'post'[0m

2021-05-25 18:33:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:33:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:34:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:34:28 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:34:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:34:54 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:35:02 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:35:10 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:38:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:38:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:38:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:38:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:39:03 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:39:11 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:39:18 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:53:52 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 18:53:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 18:54:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m

2021-05-25 18:54:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m获取用户列表[0m
2021-05-25 18:54:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:'is_count'[0m

2021-05-25 19:04:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 19:04:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 19:05:03 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 19:05:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 19:06:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 19:06:22 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生未知异常:ulist_total() missing 1 required positional argument: 'data'[0m

2021-05-25 19:06:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 19:17:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 19:17:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-25 19:17:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-25 19:17:56 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 19:18:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m

2021-05-25 19:18:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：test[0m
2021-05-25 19:18:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户删除失败,发生异常:User matching query does not exist.[0m

2021-05-25 20:18:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 20:19:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 20:36:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 20:36:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 20:58:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 20:58:10 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 21:00:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-25 21:00:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:User matching query does not exist.[0m

2021-05-25 21:05:18 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:05:24 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 21:05:29 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-25 21:05:29 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:User matching query does not exist.[0m

2021-05-25 21:05:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-25 21:05:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:User matching query does not exist.[0m

2021-05-25 21:07:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:07:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-25 21:07:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:User matching query does not exist.[0m

2021-05-25 21:07:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:07:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-25 21:07:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:User matching query does not exist.[0m

2021-05-25 21:08:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-25 21:08:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-25 21:08:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:09:15 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:11:30 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:11:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 21:12:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户删除操作，操作者为：admin[0m

2021-05-25 21:12:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-25 21:12:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-25 21:12:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-25 21:12:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,昵称 test 已经存在[0m

2021-05-25 21:13:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:13:30 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:14:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:14:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:15:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:15:47 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:17:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:17:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 21:17:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:18:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:18:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:19:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:19:10 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:19:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-25 21:20:10 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:29:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-25 21:29:52 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-25 21:30:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-25 21:30:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:User matching query does not exist.[0m

2021-05-26 17:22:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 17:22:54 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 17:25:19 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:04:05 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:04:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 20:05:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:05:54 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 20:06:35 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生异常:Expecting value: line 1 column 1 (char 0)[0m

2021-05-26 20:06:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:06:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生异常:Expecting value: line 1 column 1 (char 0)[0m

2021-05-26 20:10:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:10:30 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:20:28 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:20:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 20:21:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m获取失败，发生异常:Object of type QuerySet is not JSON serializable[0m

2021-05-26 20:24:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:28:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:28:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 20:30:29 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:47:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:47:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 20:48:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-26 20:48:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:int() argument must be a string, a bytes-like object or a number, not 'QuerySet'[0m

2021-05-26 20:50:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:50:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m
2021-05-26 20:50:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:'QuerySet' object has no attribute 'is_active'[0m

2021-05-26 20:51:35 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 20:51:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-26 20:51:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-26 20:51:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-26 20:52:05 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m更新禁用状态，操作者为：admin[0m

2021-05-26 21:03:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:04:05 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 21:07:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:19:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 21:21:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Expecting value: line 2 column 13 (char 14)[0m

2021-05-26 21:22:18 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m已更新test的禁用状态，操作者为：admin[0m

2021-05-26 21:22:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m已更新test的禁用状态，操作者为：admin[0m

2021-05-26 21:44:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:44:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 21:44:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword 'total' into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 21:45:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:45:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword 'total' into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 21:47:51 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:48:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:49:02 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword 'password,username' into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 21:49:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:49:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword "'password','username'" into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 21:49:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:50:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword "'password','username'" into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 21:50:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:50:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 21:50:53 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword 'password,username' into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 21:53:24 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 21:53:25 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:'list' object has no attribute 'split'[0m

2021-05-26 22:12:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:12:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:13:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 22:13:15 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword "['password', 'username']" into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 22:14:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:14:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:'str' object cannot be interpreted as an integer[0m

2021-05-26 22:15:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:15:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:'NoneType' object has no attribute 'split'[0m

2021-05-26 22:15:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:15:33 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:'str' object cannot be interpreted as an integer[0m

2021-05-26 22:18:21 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:18:24 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword "['password', 'username']" into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 22:18:56 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:18:59 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Cannot resolve keyword "'password', 'username'" into field. Choices are: auth_token, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mouldlist, password, phone, realname, user_permissions, username, usertype[0m

2021-05-26 22:35:26 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:35:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 22:35:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:'control'[0m

2021-05-26 22:38:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:38:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:'control'[0m

2021-05-26 22:39:15 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Object of type QuerySet is not JSON serializable[0m

2021-05-26 22:40:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:40:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Object of type User is not JSON serializable[0m

2021-05-26 22:42:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m指定用户参数获取失败，发生异常:Object of type User is not JSON serializable[0m

2021-05-26 22:51:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:51:33 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-26 22:52:54 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-26 22:53:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-26 22:53:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-26 22:53:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test11[0m
2021-05-26 22:53:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-26 22:53:53 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test111[0m
2021-05-26 22:53:53 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-26 22:53:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1111[0m
2021-05-26 22:53:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-26 22:54:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test11111[0m
2021-05-26 22:54:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 16:21:55 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 16:22:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 18:14:20 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:14:25 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:encryp_add() takes 1 positional argument but 2 were given[0m

2021-05-27 18:18:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:19:03 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:encryp_add() takes 1 positional argument but 2 were given[0m

2021-05-27 18:25:58 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:26:00 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:object of type 'builtin_function_or_method' has no len()[0m

2021-05-27 18:27:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:27:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:encryp_add() takes 1 positional argument but 2 were given[0m

2021-05-27 18:28:49 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:28:51 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m
2021-05-27 18:28:51 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:Object of type method is not JSON serializable[0m

2021-05-27 18:29:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:29:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 18:30:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 18:30:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 19:56:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 19:56:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m发生异常:login() missing 1 required positional argument: 'user'[0m

2021-05-27 20:14:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:14:52 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 20:14:56 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m登陆失败，用户名或者密码错误，操作者为：admin[0m

2021-05-27 20:27:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:27:18 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m登陆失败，用户名或者密码错误，操作者为：admin[0m

2021-05-27 20:27:23 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 20:55:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:55:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:56:53 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:57:24 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:59:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:59:39 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 20:59:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:02:30 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:02:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:02:45 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:05:10 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:05:13 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:05:13 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:07:24 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:07:26 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:07:26 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:10:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:10:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:10:09 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:10:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:10:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:10:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:11:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:11:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:11:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:12:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:12:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:12:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:Unicode-objects must be encoded before hashing[0m

2021-05-27 21:17:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:17:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m

2021-05-27 21:17:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:'builtin_function_or_method' object has no attribute 'encode'[0m

2021-05-27 21:18:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:18:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 21:18:08 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 21:20:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:20:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 21:26:19 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:26:54 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:local variable 'data' referenced before assignment[0m

2021-05-27 21:28:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-27 21:28:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 21:41:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:42:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-27 21:42:07 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 21:44:51 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:45:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test2[0m
2021-05-27 21:45:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 21:46:06 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 21:52:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:52:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 21:53:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test3[0m
2021-05-27 21:53:04 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 21:57:44 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 21:57:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test4[0m
2021-05-27 21:57:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:02:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:02:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test4[0m
2021-05-27 22:02:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,登录名 test4 已经存在[0m

2021-05-27 22:02:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test5[0m
2021-05-27 22:02:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:11:48 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:11:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 22:12:05 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:12:05 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:12:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:13:02 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:13:02 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,登录名 test6 已经存在[0m

2021-05-27 22:13:11 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:13:11 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:15:16 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:15:19 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:15:19 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,登录名 test6 已经存在[0m

2021-05-27 22:15:29 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:15:29 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:__init__() missing 1 required positional argument: 'keys'[0m

2021-05-27 22:16:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:16:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:16:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:__init__() missing 1 required positional argument: 'keys'[0m

2021-05-27 22:17:38 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:17:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test6[0m
2021-05-27 22:17:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:24:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:25:01 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 22:31:36 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:31:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m管理员登陆成功，操作者为：admin[0m

2021-05-27 22:31:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-27 22:31:57 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:(1406, "Data too long for column 'password_md5' at row 1")[0m

2021-05-27 22:33:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-27 22:33:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:34:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:34:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-27 22:34:34 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m用户添加失败,登录名 test 已经存在[0m

2021-05-27 22:34:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test[0m
2021-05-27 22:34:43 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:35:35 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:35:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：test1[0m
2021-05-27 22:35:41 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:37:32 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:40:33 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:40:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:41:29 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:41:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 22:41:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:(1406, "Data too long for column 'password_md5' at row 1")[0m

2021-05-27 22:41:54 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 22:42:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 22:42:14 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 22:48:27 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:27:31 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:28:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:28:52 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:29:42 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:30:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:30:22 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 23:30:22 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:IV is not meaningful for the ECB mode[0m

2021-05-27 23:30:47 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:30:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m执行用户添加操作，操作者为：admin[0m
2021-05-27 23:30:50 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m用户添加成功,即时生效[0m

2021-05-27 23:32:22 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:34:37 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:local variable 'data' referenced before assignment[0m

2021-05-27 23:35:12 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:35:17 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:local variable 'data' referenced before assignment[0m

2021-05-27 23:35:40 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:8" - debug - DEBUG - [0;30;42m加载路由表...[0m

2021-05-27 23:35:46 - simple - "/mnt/hgfs/WORKSMB/zjsys/adminapi/logdb.py:6" - error - ERROR - [0;30;45m添加失败，发生异常:local variable 'data' referenced before assignment[0m

